# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
        swift: ["5.3"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Switch to xcode 16.3
      run: sudo xcode-select -s /Applications/Xcode_16.2.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
